name: ghdockerbuild
on:
  pull_request:
jobs:
  publish-toolbox-image:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      if: github.event.pull_request.merged == true
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GLOGAR_TOOLBOX }}

    - name: Build the toolbox Docker image
      if: github.event.pull_request.merged == true
      run: |
        docker build . --tag ghcr.io/gregorlogar991/toolbox:latest
        docker run ghcr.io/gregorlogar991/toolbox:latest
        docker push ghcr.io/gregorlogar991/toolbox:latest
