name: ghlint
on:
  push:
    branches: master
jobs:
  publish-toolbox-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: DockerLint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master
