name: publish
on:
  pull_request:
  push:
    branches: master
jobs:
  publish-toolbox-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: DockerLint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GLOGAR_TOOLBOX }}

    - name: Build the toolbox Docker image
      run: |
        docker build . --tag ghcr.io/gregorlogar991/toolbox:latest
        docker run ghcr.io/gregorlogar991/toolbox:latest
        docker push ghcr.io/gregorlogar991/toolbox:latest
